-- Acharya Design Week: online announcements table
-- Run this once in Supabase Dashboard -> SQL Editor.

create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  author text not null,
  audience text not null check (audience in ('All clubs', 'Amethyst Club', 'Cobalt Club', 'Ruby Club', 'Martian Club', 'Emerald Club', 'Amber Club')),
  message text not null,
  created_at timestamptz not null default now()
);

alter table public.announcements enable row level security;

-- Demo policies for the current username-only prototype.
-- Replace the insert policy with an authenticated faculty/committee policy before production use.
drop policy if exists "Anyone can read announcements" on public.announcements;
create policy "Anyone can read announcements"
  on public.announcements for select
  using (true);

drop policy if exists "Prototype can publish announcements" on public.announcements;
create policy "Prototype can publish announcements"
  on public.announcements for insert
  with check (true);

grant select, insert on public.announcements to anon, authenticated;
grant usage, select on sequence public.announcements_id_seq to anon, authenticated;
